name: Print PR Patch Content
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  local-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: "smart-review"
    - name: npm install
      run: |
        cd smart-review
        npm install
    - name: Print patch content
      uses: ./smart-review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}